## PCA

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.decomposition import PCA

In [3]:
from sklearn import datasets

In [4]:
dataset = datasets.load_iris()

In [10]:
X = dataset['data']
y = dataset['target']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [13]:
pca = PCA(n_components=3)

In [16]:
X_train = pca.fit_transform(X_train)

In [17]:
X_train

array([[ 1.02799542, -0.31467953,  0.15777091],
       [-2.11536297,  0.67467328,  0.20846312],
       [ 3.89502341,  0.16130146,  0.50806456],
       [ 0.92012482, -0.26216508, -0.08405848],
       [ 1.43241848,  0.08771424,  0.52011321],
       [-2.31238038,  0.21086871,  0.19339783],
       [-0.06343796, -0.36810704, -0.13518426],
       [ 2.01955863,  0.34915835, -0.05540831],
       [ 1.065967  , -0.69746746,  0.42051324],
       [ 0.24875725, -0.45321761,  0.11484634],
       [ 1.75895639,  0.18798943, -0.23108758],
       [-2.67489169, -0.44976269,  0.15911579],
       [-2.53198124,  0.37689958,  0.33428697],
       [-2.56496231, -0.32613664,  0.16074204],
       [-2.49739987,  0.34844574, -0.17143788],
       [ 1.18995309,  0.20368068, -0.16783406],
       [ 2.45236354, -0.07194011, -0.31883064],
       [ 0.16363931, -0.73112098,  0.13406626],
       [ 0.75266083, -0.52126707, -0.13593419],
       [ 2.26765321, -0.2598825 , -0.25427498],
       [-2.52407281, -0.37941911, -0.090

In [18]:
# give corordinates of eigen vector
pca.components_

array([[ 0.35148439, -0.10792186,  0.8557313 ,  0.36405431],
       [ 0.59309703,  0.79131683, -0.14815339,  0.01020597],
       [ 0.67808168, -0.52707912, -0.13474002, -0.49420438]])

In [19]:
# how many variance getting captured with the help of this PCA model
pca.explained_variance_ratio_

array([0.93858749, 0.04474854, 0.01156705])