### Logistic Regression Implementation

## 1. Loading IRIS DATASET

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [7]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

## 2. creating a Dataframe from our Dataset

In [11]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
import pandas as pd
import numpy as np

In [14]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
df['Target'] = dataset.target

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

# BINARY CLASSIFICATION

In [19]:
df_copy = df[df['Target']!=2]

In [21]:
df_copy['Target'].unique()

array([0, 1])

In [22]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

## 3. INDEPENDENT AND DEPENDENT FEATURES

In [36]:
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:, -1]

## 4. TRAIN TEST SPLIT

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

## 5. PERFORM LOGISTIC REGRESSION

In [39]:
from sklearn.linear_model import LogisticRegression

In [41]:
classifier = LogisticRegression()

In [42]:
classifier.fit(X_train, y_train)

LogisticRegression()

## 6. PREDICTION ON y DATA

In [44]:
y_pred = classifier.predict(X_test)

In [45]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## 7. CONFUSION MATRIX , ACCURACY SCORE, CLASSIFICATION REPORT 

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report

In [52]:
confusion_matrix(y_pred, y_test)

array([[12,  0],
       [ 0,  8]])

In [54]:
accuracy_score(y_pred, y_test)

1.0

In [56]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## HYPERPARAMENTER TUNING

## 8. GRIDSEARCHCV

In [57]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [59]:
parameters = {'penalty' : ('l1', 'l2', 'elasticnet', None), 'C' : [1, 10, 20]}

In [62]:
clf = GridSearchCV(classifier, param_grid=parameters, cv= 5)

## 9. SPLITTING of train data to Validation data

In [63]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [64]:
## to check best paramenters
clf.best_params_

{'C': 1, 'penalty': 'l2'}

## 10.. Regenarate Classifier with best suitable parameters

In [65]:
classifier = LogisticRegression(C=1, penalty='l2')

In [66]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1)

In [67]:
y_pred = classifier.predict(X_test)

In [68]:
confusion_matrix(y_pred, y_test)

array([[12,  0],
       [ 0,  8]])

In [69]:
accuracy_score(y_pred, y_test)

1.0

In [70]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



### 11. Randomized SEARCH CV

In [71]:
from sklearn.model_selection import RandomizedSearchCV

In [79]:
random_clf = RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv =5)

In [80]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [81]:
random_clf.best_params_

{'penalty': None, 'C': 1}

In [83]:
classifier = LogisticRegression(C=1, penalty=None)

In [84]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1, penalty=None)

In [85]:
y_pred = classifier.predict(X_test)

In [86]:
confusion_matrix(y_pred, y_test)

array([[12,  0],
       [ 0,  8]])

In [87]:
accuracy_score(y_pred, y_test)

1.0

In [88]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

